version: '3'
services:
  logger:
    build:
      context: ./  # Path to the directory containing your Dockerfile
    container_name: logger
    restart: always
    volumes:
      - ./log:/app/log
    network_mode: "host"